# Generated by Django 4.2.10 on 2024-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dr_Degree', models.CharField(max_length=150)),
                ('Dr_name', models.CharField(max_length=200)),
                ('Dr_Specilization', models.CharField(max_length=200)),
            ],
        ),
    ]
