# Generated by Django 4.2.10 on 2024-05-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_ID', models.CharField(max_length=100, unique=True)),
                ('P_Name', models.CharField(max_length=100)),
                ('P_Age', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Dr_name',
            new_name='Dr_Name',
        ),
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS_App.patient')),
                ('room_number', models.IntegerField()),
                ('admission_date', models.DateField()),
            ],
            bases=('HMS_App.patient',),
        ),
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS_App.patient')),
                ('appointment_date', models.DateField()),
            ],
            bases=('HMS_App.patient',),
        ),
    ]
